name: Kratos AI Reviewer
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Deps
        run: pip install huggingface_hub chromadb requests python-dotenv

      - name: Get Diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt
          
      - name: Index Project Context
        env:
          DB_PATH: "kratos_memory" 
        run: python src/index_repo.py 

      - name: Run Kratos
        env:
          # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITH_TOKEN: ${{ secrets.GITH_TOKEN }}
          DB_PATH: "kratos_memory"
          # DB_PATH: ${{ secrets.DB_PATH }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python src/main.py ${{ github.repository }} ${{ github.event.pull_request.number }}